### PR TITLE
Add inner shadows to quest map

### LINKED ISSUE #490: Add an inner shadow to the Maps/Cytoscape canvas
Currently the maps just cut off as your pan around with middle mouse click.  Needs a visual indicator of the edge of the canvas.
Peek 2020-05-05 11-32

### PR DESCRIPTION
**Pull request by yujinyuz**
Not that good with css so pardon! any change request would be welcome 😸 

Screen Shot 2020-05-09 at 3 52 34 PM

Screen Shot 2020-05-09 at 3 50 56 PM

Closes #490

### CODE REVIEW

**Comment by tylerecouture** [comment]
Good start!  A few suggestions:
-Use the same dark shadow on both (the glow on dark theme looks weird)
- Add a minimum height to the canvas so it at least goes to the bottom of the buttons on the left
- Can you add a screenshot to show what it looks like when you pan to the side and the map goes partially "under"

**Comment by tylerecouture** [comment]
Also, not sure why the I put the css is in the file directly?  can you move to a css file?

**Comment by tylerecouture** [comment]
oooh, needs rounded corners to match the rest of the UI too (couldn't see them before!)

**Comment by yujinyuz** [comment]
quest-map

**Pull request merged**
