### PR TITLE
Redirect student if quest is in progress

### LINKED ISSUE #455: Redirect student to in-progress quest if they try to start it again
There is a user error that is common enough that we should handle it:

A student starts a quest, then for some reason hits back on their browser,  and then tries to start the quest again.  But since it's already been started (and appearing in their in progress quests), they get a 404 error.

Instead, if they try to start (via "/quests/23/start/" for example) a quest a second time, instead it should just redirect them to the already in-progress quest.

### PR DESCRIPTION
**Pull request by yujinyuz**
Closes #455

### CODE REVIEW

**Comment by yujinyuz** [comment]
@tylerecouture Yes. I am adding tests. I'm still trying to figure out how to add a quest in the current semester since `QuestSubmission.objects.not_all_completed` returns an empty queryset.

**Comment by tylerecouture** [comment]
Under what conditions does that happen?

**Comment by yujinyuz** [comment]
> Under what conditions does that happen? Do you mean during a test?

Yes during test.  I think a 404 happens in the test case since a quest isn't assigned in a particular semester

**Comment by tylerecouture** [comment]
Ah, OK.  How about I'll figure out the test for this one and you can use it for future reference.

**Comment by yujinyuz** [comment]
Sure @tylerecouture thanks!

**Comment by tylerecouture** [comment]
@yujinyuz 

A few notes for you on this PR:
1. [redirect](https://docs.djangoproject.com/en/3.0/topics/http/shortcuts/#redirect) accepts a model object, so you don't have to go through all that convoluted code to get redirect to work! haha, just go `redirect(quest_submission)` and it will work as long as `get_absolute_url()` is defined on the model, which it is.  I probably have some of that convoluted code elsewhere myself, but it's not necessary (feel free to fix if you find!)... I even do it slightly further down in the same method!
2. If you look further down the code in this method, you can see that there was already an attempt to solve this problem (apparently from me 5 years ago according to git blame!)
```
    new_sub = QuestSubmission.objects.create_submission(request.user, quest)
    # if new_sub is None:
    #     print("This quest is not available, why is it showing up?")
    #     raise Http404 #shouldn't get here
    # should just do this, but the redirect is screwing up with the tour...
    # return redirect('quests:submission', submission_id = new_sub.id)

    if new_sub is None:  # might be because quest was already started
        # so try to get the started Quest
        sub = QuestSubmission.objects.all_for_user_quest(request.user, quest, True).last()
        if sub is None:
            raise Http404
    else:
        sub = new_sub
```

And in the end, should redirect to that submission anyway.  So why doesn't it do it?  I'll fix it up as I write the test for this method.  I  don't have a thorough test suite for the views that cehcks all the possible logic paths, so this will be the start!  I'm going to comment it thoroughly so hopefully you can more easily start adding appropriate tests for each of your PRs

**Pull request merged**
