### PR TITLE
Use site config for favicon

### LINKED ISSUE #250: Suggestion - Ability to change favicon in settings

### PR DESCRIPTION
**Pull request by yujinyuz**
Closes #250 

Tested and working on my local

Screen Shot 2020-04-13 at 9 08 43 PM

### CODE REVIEW

**Comment by tylerecouture** [comment]
Does this work in all browsers?  It doesn't seem to work in Firefox: (uploaded Grass.png as a test but it's still showing the blue T
image

**Comment by yujinyuz** [comment]
This is quite weird.

I've tried accessing my multi-tenant in firefox via http://q.localhost:8000/ but it say's 

Screen Shot 2020-04-17 at 8 12 13 AM

Screen Shot 2020-04-17 at 8 12 27 AM

My firefox version is 75.0 (64-bit).

What version are you using? I can access it perfectly fine with chrome

**Comment by tylerecouture** [comment]
I'm using 75.0 on Ubuntu.  Weird suggestion, but did you try typing in
http://

**Comment by yujinyuz** [comment]
Yes. I did. I'm also on Firefox 75.0 (macOS) but no luck. Still can't access

**Comment by yujinyuz** [comment]
I don't have any extensions installed so I'm not quite sure what's wrong. It's working in Chrome so it's probably a browser issue

**Pull request merged**
