### PR TITLE
Utilities app correctly done?

### PR DESCRIPTION
**Pull request by nanbul98**
Just want to have you double check and see if I completed this correctly?

### CODE REVIEW

**Comment by tylerecouture** [comment]
I don't think you committed the files for the Utilities app! only the models.py for quests is included here....?

**Comment by tylerecouture** [comment]
Also, don't you need to update settings'py to include the new app?  Have you tested this? does it work?

**Comment by tylerecouture** [comment]
Where's the utilities app itself though? as in :`src/utitlies` and `src/utitlies/models.py' etc etc? Those weren't added in any of these commits.

**Comment by nanbul98** [comment]
is this good?

**Comment by tylerecouture** [comment]
Sorry it took me so long to look at this =(.   The Quest model is an extension of the XPItem model which already has an icon attribute, so perhaps revert the Quest model and just leave that for now so I can accept the utilities app by itself and think about how to switch from the current icons to the new Utilities.icon model.

**Pull request closed without merging**
